"""link leads to users

Revision ID: 4554fc2a2cf3
Revises: 9342c9239684
Create Date: 2026-08-14 05:25:04.645580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4554fc2a2cf3'
down_revision: Union[str, Sequence[str], None] = '9342c9239684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_leads_user_id'), 'leads', ['user_id'], unique=False)
    op.create_foreign_key(None, 'leads', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_index(op.f('ix_leads_user_id'), table_name='leads')
    op.drop_column('leads', 'user_id')
    # ### end Alembic commands ###
